# Generated by Django 4.2.7 on 2023-12-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='apee.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='apee.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score_team_1', models.IntegerField()),
                ('score_team_2', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='apee.league')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_1', to='apee.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_2', to='apee.team')),
            ],
        ),
    ]
